# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    # default configuration for services in *this* file

    app.jwt_auth:
        class: AppBundle\Services\JwtAuth
        arguments: ["@doctrine.orm.entity_manager"]

    app.helpers:
        class: AppBundle\Services\Helpers
        arguments: ["@app.jwt_auth"]

